import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import Navbar from "./lib/components/navbar";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box w="100%" h="100%" bgGradient="linear(to-t, #30cfd0, #330867)">
            <Navbar></Navbar>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
